# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"initialise_spotify_client": "01-discography.ipynb",
         "setup_client_scopes": "02-playlists.ipynb",
         "try_accept": "01-discography.ipynb",
         "load_artist_discog": "01-discography.ipynb",
         "extract_album_dates": "01-discography.ipynb",
         "name_2_album_meta": "01-discography.ipynb",
         "check_release_date_consistency": "01-discography.ipynb",
         "df_album_dates_to_spotify_meta": "01-discography.ipynb",
         "extract_all_songs_in_albums": "01-discography.ipynb",
         "retrieve_track_analysis": "01-discography.ipynb",
         "get_album_art": "02-playlists.ipynb",
         "get_album_data": "02-playlists.ipynb",
         "get_track_data": "02-playlists.ipynb",
         "get_playlist_track_metadata": "02-playlists.ipynb",
         "retrieve_playlist_df": "02-playlists.ipynb",
         "retrieve_latest_discover_weekly": "03-pipeline.ipynb",
         "update_discover_weekly_archive": "03-pipeline.ipynb",
         "update_discover_weekly_archive_pipeline": "03-pipeline.ipynb"}

modules = ["discography.py",
           "playlists.py",
           "pipeline.py"]

doc_url = "https://AyrtonB.github.io/Spotify-Watch/"

git_url = "https://github.com/AyrtonB/Spotify-Watch"

def custom_doc_links(name): return None
