# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03-pipeline.ipynb (unless otherwise specified).

__all__ = ['retrieve_latest_discover_weekly', 'update_discover_weekly_archive',
           'update_discover_weekly_archive_pipeline']

# Cell
import pandas as pd

from spotifywatch import playlists
from dagster import execute_pipeline, pipeline, solid, Field

import os
import dotenv

# Cell
@solid()
def retrieve_latest_discover_weekly(_, playlist_id: str='spotify:playlist:37i9dQZEVXcOwrS8NC07JJ'):
    df_latest_discover_weekly = playlists.retrieve_playlist_df(playlist_id)

    return df_latest_discover_weekly

@solid()
def update_discover_weekly_archive(_, df_latest_discover_weekly, discover_weekly_archive_fp: str='data/playlists/discover_weekly.csv'):
    df_discover_weekly_archive = (pd
                                  .read_csv(discover_weekly_archive_fp)
                                  .append(df_latest_discover_weekly)
                                  .drop_duplicates()
                                 )

    df_discover_weekly_archive.to_csv(discover_weekly_archive_fp, index=False)

    return df_discover_weekly_archive

# Cell
@pipeline
def update_discover_weekly_archive_pipeline():
    df_latest_discover_weekly = retrieve_latest_discover_weekly()
    update_discover_weekly_archive(df_latest_discover_weekly)